import type { Metadata } from "next";
import "aos/dist/aos.css"; // You can also use <link> for styles
import "./globals.scss";
import AOSInit from "src/components/AOSInit/AOSInit";
import { fontInter } from "src/fonts/fonts";
import Header from "src/layout/Header/Header";
import Footer from "src/layout/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <AOSInit />
            <body className={`${fontInter.className} relative`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
